
CREATE TABLE IF NOT EXISTS Role (
    RoleID INTEGER PRIMARY KEY AUTOINCREMENT,
    RoleName TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS User (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT NOT NULL,
    RoleID INTEGER NOT NULL,
    FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
);

CREATE TABLE IF NOT EXISTS Subject (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    SubjectLeader INTEGER NOT NULL,
    FOREIGN KEY (SubjectLeader) REFERENCES User(UserID)
);

CREATE TABLE IF NOT EXISTS Course (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Award TEXT NOT NULL,
    Title TEXT NOT NULL,
    CourseLeader INTEGER NOT NULL,
    SubjectID INTEGER NOT NULL,
    FOREIGN KEY (CourseLeader) REFERENCES User(UserID),
    FOREIGN KEY (SubjectID) REFERENCES Subject(ID)
);

CREATE TABLE IF NOT EXISTS Module (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Code TEXT NOT NULL,
    Title TEXT NOT NULL,
    Level INTEGER NOT NULL,
    ModuleLeader INTEGER NOT NULL,
    CourseID INTEGER NOT NULL,
    FOREIGN KEY (ModuleLeader) REFERENCES User(UserID),
    FOREIGN KEY (CourseID) REFERENCES Course(ID)
);

